# escape=`
FROM microsoft/powershell:windowsservercore
LABEL maintainer='Travis Plunk <github@ez13.net>'
LABEL readme.md="https://github.com/TravisEz13/microsoft.windowsservercore_build-tools/blob/master/readme.md"
LABEL description="This Dockerfile for Windows Server Core with various build tools installed.  See readme on docker hub for licensing."

SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-command"]
# Install Git, NuGet, cMake and WixToolSet
# Git installs to C:\Program Files\Git
# nuget installs to C:\ProgramData\chocolatey\bin\NuGet.exe
# Cmake installs to C:\Program Files\CMake\
COPY containerFiles/dockerInstall.psm1 containerFiles/dockerInstall.psm1
RUN Import-Module ./containerFiles/dockerInstall.psm1; `
    Install-ChocolateyPackage -PackageName git -Executable git.exe; `
    Install-ChocolateyPackage -PackageName nuget.commandline -Executable nuget.exe; `
    Install-ChocolateyPackage -PackageName cmake.install -Executable cmake.exe -Cleanup

# Install Win 10 SDK
ADD https://github.com/wixtoolset/wix3/releases/download/wix311rtm/wix311-binaries.zip /wix.zip
COPY containerFiles/wix.psm1 containerFiles/wix.psm1  
RUN Import-Module ./containerFiles/wix.psm1; `
    Install-WixZip -zipPath \wix.Zip

# Install Win 10 SDK
COPY containerFiles/sdkCommon.psm1 containerFiles/sdkCommon.psm1
COPY containerFiles/win10sdk.psm1 containerFiles/win10sdk.psm1
RUN Import-Module ./containerFiles/win10sdk.psm1; `
    Install-Win10Sdk

# install VCpp build tools
COPY containerFiles/vcBuildTools.psm1 containerFiles/vcBuildTools.psm1
RUN Import-Module ./containerFiles/vcBuildTools.psm1; `
    Install-VcBuildTools

# copy tests to verify containter     
COPY containerTests/ containerFiles/tests/
ENTRYPOINT ["powershell", "-c"]


#FROM microsoft/powershell:windowsservercore
#LABEL maintainer='Travis Plunk <github@ez13.net>'
#LABEL readme.md="https://github.com/TravisEz13/microsoft.windowsservercore_build-tools/blob/master/readme.md"
#LABEL description="This Dockerfile for Windows Server Core with various build tools installed.  See readme on docker hub for licensing."

#COPY --from=0 C:/Program Files/Git/ C:/Program Files/Git/
#COPY --from=0 C:/Program Files/CMake/ C:/Program Files/CMake/
#COPY --from=0 C:/ProgramData/chocolatey/bin/ C:/ProgramData/chocolatey/bin/

# Setup the path
#COPY containerFiles/dockerInstall.psm1 containerFiles/dockerInstall.psm1
#RUN Import-Module ./containerFiles/dockerInstall.psm1; `
#    Append-Path -path C:\Program Files\Git\bin; `
#    Append-Path -path C:\Program Files\CMake\bin; `
#    Append-Path -path C:\ProgramData\chocolatey\bin; `
